name: back_in_town_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  marquee: ^2.3.0
  http: ^1.2.0        # Per chiamare le API di AzuraCast
  just_audio: ^0.9.36 # Il miglior player audio per Flutter
  web_socket_channel: ^3.0.0
  audio_session: ^0.1.21
  webview_flutter: ^4.13.1
  just_audio_background: ^0.0.1-beta.17
  url_launcher: ^6.2.4       # Per aprire link esterni
  font_awesome_flutter: ^10.7.0 # Per l'icona ufficiale WhatsApp

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
